Repository harakeke-2019/track-a-grad, pull requests merged in 2019-03, with the labels that each got.

#94 Jason lane bandaid brigade
  client/components/GraduateFeed.jsx
  client/components/GraduateProfile.jsx
  server/db/seeds/work_statuses.js
  server/db/users.js
Labels: Client Side, Front End, React-Redux

#97 95edit component
  client/components/EditProfile.jsx
Labels: Client Side

#104 contact form created
  client/components/ContactForm.jsx
Labels: Front End

#117 116 registration page
  client/components/App.jsx
  client/components/DashBoardHeader.jsx
  client/components/Nav.jsx
  client/components/Registration.jsx
  server/db/seeds/profiles.js
Labels: Front End

#119 have added style loaders for sitewide css
  client/components/App.jsx
  client/components/GraduateDashboard/GraduateDashboard.jsx
  client/components/contactForm/ContactForm.jsx
  client/components/contactForm/contact.css
  package.json
  server/public/main.css
  webpack.config.js
  yarn.lock
Labels: Front End - UI - UX

#123 fixed registration fields to match with users table
  client/components/Registration.jsx
Labels: Front End

#124 120cssfolder
  client/components/App.jsx
  client/components/DashboardHeader/DashBoardHeader.jsx
  client/components/DashboardHeader/dashboardheader.css
  client/components/Description/Description.jsx
  client/components/Description/description.css
  client/components/EditProfile/EditProfile.jsx
  client/components/EditProfile/editprofile.css
  client/components/FeedHeader.jsx
  client/components/GraduateDashboard/GraduateDashboard.jsx
  client/components/GraduateDashboard/graduatedashboard.css
  client/components/GraduateFeed/GraduateFeed.jsx
  client/components/GraduateFeed/graduatefeed.css
  client/components/GraduateProfile/GraduateProfile.jsx
  client/components/GraduateProfile/graduateprofile.css
  client/components/Info/Info.jsx
  client/components/Info/info.css
  client/components/Nav/Nav.jsx
  client/components/Nav/nav.css
  client/components/Registration/Registration.jsx
  client/components/Registration/registration.css
  client/components/Signin/SignIn.jsx
  client/components/Signin/signin.css
Labels: Front End - UI - UX

#131 Lanelps styling
  client/components/DashboardHeader/DashBoardHeader.jsx
  client/components/GraduateDashboard/GraduateDashboard.jsx
  client/components/GraduateDashboard/graduatedashboard.css
  client/components/GraduateFeed/GraduateFeed.jsx
  client/components/GraduateProfile/GraduateProfile.jsx
  client/components/GraduateProfile/graduateprofile.css
  client/components/Nav/Nav.jsx
  client/components/Nav/nav.css
Labels: Client Side, Front End, Front End - UI - UX

#132 More styling for graduate dashboard
  client/components/DashboardHeader/DashBoardHeader.jsx
  client/components/DashboardHeader/dashboardheader.css
  client/components/GraduateDashboard/GraduateDashboard.jsx
  client/components/GraduateDashboard/graduatedashboard.css
  client/components/Info/Info.jsx
Labels: Client Side, Front End, Front End - UI - UX

#135 completed nav
  client/components/GraduateDashboard/GraduateDashboard.jsx
  client/components/GraduateFeed/GraduateFeed.jsx
  client/components/Nav/Nav.jsx
  client/components/Nav/nav.css
Labels: Front End - UI - UX

#134 131 graduate feed
  client/components/GraduateProfile/GraduateProfile.jsx
  client/components/GraduateProfile/graduateprofile.css
  server/public/main.css
Labels: Front End - UI - UX

#136 Fixedstyling
  client/components/DashboardHeader/DashBoardHeader.jsx
  client/components/EditProfile/EditProfile.jsx
  client/components/GraduateDashboard/GraduateDashboard.jsx
  client/components/GraduateDashboard/graduatedashboard.css
  client/components/GraduateFeed/GraduateFeed.jsx
  client/components/Info/Info.jsx
  client/components/Info/info.css
  client/components/Nav/nav.css
  client/components/Registration/Registration.jsx
  client/components/Registration/registration.css
  client/components/Signin/SignIn.jsx
  client/components/Signin/signin.css
  server/public/images/background.png
  server/public/images/backimage.png
  server/public/images/register-image.png
  server/public/main.css
Labels: Front End - UI - UX

#143 edit page to update load or update profile created
  client/components/App.jsx
  client/components/EditForm/EditForm.jsx
  client/components/EditForm/editform.css
Labels: Front End, React-Redux

#144 have added redux edit
  client/actions/users.js
  client/components/App.jsx
  client/components/EditProfile/EditProfile.jsx
  client/components/EditProfile/Viewinfo.jsx
  client/reducers/edit.js
  client/reducers/index.js
Labels: Front End

#156 140 update db routes
  client/components/EditForm/EditForm.jsx
  client/components/Form/Form.jsx
  client/components/GraduateDashboard/GraduateDashboard.jsx
  server/db/seeds/profiles.js
  server/db/seeds/users.js
  server/db/seeds/work_statuses.js
  server/db/users.js
Labels: Client Side, Database, Front End, React-Redux, Routing, Server Side

#166 162 styling grad form
  client/components/Form/Form.jsx
  client/components/Form/form.css
  client/components/GraduateDashboard/GraduateDashboard.jsx
  client/components/GraduateDashboard/graduatedashboard.css
  client/components/Nav/Nav.jsx
  server/public/index.html
  server/public/main.css
Labels: Front End - UI - UX

#169 fixed styling
  client/components/DashboardHeader/DashBoardHeader.jsx
  client/components/DashboardHeader/dashboardheader.css
  client/components/EditForm/editform.css
  client/components/Form/Form.jsx
  client/components/Form/form.css
  client/components/GraduateDashboard/GraduateDashboard.jsx
  client/components/GraduateFeed/GraduateFeed.jsx
  client/components/GraduateFeed/graduatefeed.css
  client/components/GraduateProfile/graduateprofile.css
  client/components/Nav/Nav.jsx
  client/components/Nav/nav.css
  client/components/Registration/Registration.jsx
  client/components/Registration/registration.css
  client/components/Signin/SignIn.jsx
  client/components/Signin/signin.css
  server/public/index.html
  server/public/main.css
Labels: Front End
