Repository harakeke-2019/track-a-grad, pull requests merged in 2019-02, with the labels that each got.

#9 3 co design file architecture
  knexfile.js
  package.json
  server/auth/hash.js
  server/auth/token.js
  server/public/index.html
  server/public/main.css
  server/server.js
  yarn.lock
Labels: Planning

#22 6 front end components
  client/components/App.jsx
  client/components/ContactForm.jsx
  client/components/DashBoardHeader.jsx
  client/components/Description.jsx
  client/components/FeedHeader.jsx
  client/components/Info.jsx
  client/components/Nav.jsx
  client/components/SignIn.jsx
  client/components/StudentDashboard.jsx
  client/components/StudentFeed.jsx
  client/components/StudentProfile.jsx
Labels: Front End

#29 added more links
  client/components/Nav.jsx
Labels: Front End

#30 19 sign in layout
  client/components/SignIn.jsx
Labels: Front End

#38 18 info layout
  client/components/Info.jsx
Labels: Front End, client

#47 studentProfile
  client/components/GraduateProfile.jsx
Labels: client

#60 25 create seeds
  server/db/migrations/20190228155052_profiles.js
  server/db/migrations/20190228162238_cohorts.js
  server/db/migrations/20190228164243_work_statuses.js
Labels: Database

#61 34 testing get graduate function db
  package.json
  tests/graduates.test.js
  yarn.lock
Labels: Testing

#69 20student feed
  client/components/GraduateFeed.jsx
  client/components/GraduateProfile.jsx
Labels: Front End

#85 Imports added to client index
  client/index.js
Labels: Client Side, Front End, React-Redux

#86 action/reducer/api connected for getting graduates
  client/actions/users.js
  client/api/users.js
  client/reducers/index.js
  client/reducers/users.js
Labels: React-Redux

#88 fixed error in portfolios, profiles and added skills table and seed data
  server/db/migrations/20190228174236_portfolio.js
  server/db/migrations/20190301113225_skills.js
  server/db/seeds/skills.js
Labels: Database

#87 68 link signin
  client/components/App.jsx
  client/components/Nav.jsx
  client/components/SignIn.jsx
Labels: Client Side
